pipeline {
	agent any

	stages {
		stage("docker image") { steps {
			sh 'make -C shared_docker image'
		}}

		stage("build") { steps {
			sh 'make -C shared_docker build'
		}}
		
		stage("test") { steps {
			sh 'make -C shared_docker test'
		}}
	}
	
	post { always {
		sh 'make rm'
		junit 'build/junit.report'
		emailext body: '${JELLY_SCRIPT, template="text"}', subject: '$DEFAULT_SUBJECT', recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']]
	}}
}
